server:
  port: 9999
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 3gAn@130599
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

build:
  version: "1.0"
accounts:
  message: "Welcome to EazyBank accounts related to local APIs"
  contactDetails:
    name: "Egan Pham - Developer"
    email: "eganpham.99@gmail.com"
  onCallSupport:
    - (+84) 989 211 621
    - (+84) 989 213 418
